drop table if exists buyer_document_puppies cascade;
drop table if exists buyer_documents cascade;
drop table if exists dog_documents cascade;
drop table if exists payment_plan_puppies cascade;
drop table if exists transactions cascade;
drop table if exists payment_plans cascade;
drop table if exists puppy_updates cascade;
drop table if exists events cascade;
drop table if exists dog_registrations cascade;
drop table if exists dog_medical_records cascade;
drop table if exists puppies cascade;
drop table if exists litters cascade;
drop table if exists buyers cascade;
drop table if exists dogs cascade;

create table dogs (
  id bigint generated by default as identity primary key,
  name text not null,
  registered_name text,
  sex text not null default '',
  role text not null default '',
  date_of_birth text,
  color text,
  weight real,
  registration_number text,
  microchip_number text,
  health_testing text,
  acquired_from text,
  acquisition_date text,
  purchase_price_cents integer,
  acquisition_notes text,
  status text not null default 'Active',
  next_heat_date text,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table buyers (
  id bigint generated by default as identity primary key,
  first_name text not null default '',
  last_name text not null default '',
  email text not null default '',
  phone text,
  city text,
  state text,
  application_status text not null default 'Inquiry',
  preferred_sex text,
  preferred_color text,
  household_notes text,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table litters (
  id bigint generated by default as identity primary key,
  name text not null,
  dam_id bigint references dogs(id) on delete set null,
  sire_id bigint references dogs(id) on delete set null,
  breeding_date text,
  due_date text,
  birth_date text,
  expected_count integer,
  status text not null default 'Planned',
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table puppies (
  id bigint generated by default as identity primary key,
  litter_id bigint references litters(id) on delete cascade,
  buyer_id bigint references buyers(id) on delete set null,
  name text not null,
  sex text,
  color text,
  birth_date text,
  birth_weight real,
  current_weight real,
  status text not null default 'Available',
  price_cents integer,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table dog_medical_records (
  id bigint generated by default as identity primary key,
  dog_id bigint references dogs(id) on delete cascade,
  record_type text not null default '',
  title text not null,
  record_date text,
  provider text,
  cost_cents integer not null default 0,
  next_due_date text,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table dog_registrations (
  id bigint generated by default as identity primary key,
  dog_id bigint references dogs(id) on delete cascade,
  registry text not null default '',
  registration_number text not null default '',
  registered_name text,
  issue_date text,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table dog_documents (
  id bigint generated by default as identity primary key,
  dog_id bigint references dogs(id) on delete cascade,
  registration_id bigint references dog_registrations(id) on delete set null,
  document_type text not null default '',
  registry text,
  registration_number text,
  title text not null,
  object_key text not null unique,
  file_name text not null,
  content_type text not null,
  size_bytes integer not null default 0,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table payment_plans (
  id bigint generated by default as identity primary key,
  buyer_id bigint references buyers(id) on delete cascade,
  name text not null default 'Puppy payment plan',
  total_amount_cents integer not null default 0,
  payment_amount_cents integer not null default 0,
  term_count integer not null default 1,
  frequency text not null default 'Monthly',
  start_date text,
  next_due_date text,
  on_time_credit_cents integer not null default 0,
  credit_eligible boolean not null default true,
  status text not null default 'Active',
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table payment_plan_puppies (
  payment_plan_id bigint not null references payment_plans(id) on delete cascade,
  puppy_id bigint not null references puppies(id) on delete cascade,
  primary key (payment_plan_id, puppy_id)
);

create table transactions (
  id bigint generated by default as identity primary key,
  type text not null,
  dog_id bigint references dogs(id) on delete set null,
  buyer_id bigint references buyers(id) on delete set null,
  litter_id bigint references litters(id) on delete set null,
  puppy_id bigint references puppies(id) on delete set null,
  payment_plan_id bigint references payment_plans(id) on delete set null,
  category text,
  description text not null,
  amount_cents integer not null default 0,
  due_date text,
  paid_date text,
  status text not null default 'Pending',
  method text,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table buyer_documents (
  id bigint generated by default as identity primary key,
  buyer_id bigint references buyers(id) on delete cascade,
  payment_plan_id bigint references payment_plans(id) on delete set null,
  document_type text not null default '',
  title text not null,
  object_key text not null unique,
  file_name text not null,
  content_type text not null,
  size_bytes integer not null default 0,
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table buyer_document_puppies (
  document_id bigint not null references buyer_documents(id) on delete cascade,
  puppy_id bigint not null references puppies(id) on delete cascade,
  primary key (document_id, puppy_id)
);

create table events (
  id bigint generated by default as identity primary key,
  title text not null,
  event_type text not null,
  event_date text not null,
  event_time text,
  related_type text,
  related_id bigint,
  location text,
  status text not null default 'Scheduled',
  notes text,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create table puppy_updates (
  id bigint generated by default as identity primary key,
  puppy_id bigint references puppies(id) on delete cascade,
  title text not null,
  body text not null default '',
  week_number integer,
  weight real,
  published boolean not null default false,
  created_at text not null default now()::text,
  updated_at text not null default now()::text
);

create index dogs_name_idx on dogs(name);
create index buyers_email_idx on buyers(email);
create index puppies_litter_idx on puppies(litter_id);
create index transactions_type_idx on transactions(type);
create index events_date_idx on events(event_date);

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
